### ISSUE TITLE
Add style to "Caclulate" button on Winota's Archetype's Page

### ISSUE THREAD

**Issue by Spigushe** [Spigushe/barrins-codex#8]
Style has to be derived from:

```css
.calcul {
    text-decoration: none;
    border: 1px;
    border-radius: 0.5em;
    border-color: #ec5354;
    border-style: solid;
    padding: 0.5em;
    margin: 0;
    color: #ec5354;
}
```

- [x] Color is to be changed
- [x] Button has to be identified
